import { Dimensions, StyleSheet } from 'react-native';
const { height, width } = Dimensions.get("screen")

export default StyleSheet.create({
    container: {
        flex: 1,
    },
    screenContentContainer: {
        backgroundColor: "#000",

        height,
        width,
    },
    backgroundImage: {
        borderRadius: 31,
        borderWidth: 1,
        borderColor: "grey",
        backgroundColor: "rgba(247, 246, 246, 0.24)",
        paddingTop: 30,
        paddingBottom: 20,
        width: "100%",
    },
    stater: {
        color: "#fff",
        fontSize: 42,
        fontStyle: "normal",
        fontWeight: "700",
        textAlign: "left",
        marginTop: 130,
        marginLeft: "auto",
        marginRight: "auto",
        width: 223,
        lineHeight: 50,
    },
    stater2: {
        color: "#fff",
        fontSize: 42,
        fontStyle: "normal",
        fontWeight: "700",
        textAlign: "left",
        lineHeight: 50,
        marginLeft: "auto",
        marginRight: "auto",
        width: 223,
    },
    staterText: {
        color: "#7EAA00",
        fontSize: 63,
        fontStyle: "normal",
        fontWeight: "700",
        textAlign: "left",
        lineHeight: 80,
        marginLeft: "auto",
        marginRight: "auto",
        width: 223,
        marginBottom: 60,
    },
    textField: {
        width: "100%",
        height: 43,
        backgroundColor: "#2E2E2E",
        borderRadius: 16,
        padding: 12,
        marginBottom: 15,
    },
    tapButton: {
        marginTop: 24,
        width: "75%",
        marginLeft: 80,
        marginRight: "auto",
        height: 48,
        marginBottom: 12,
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
    },
    btnLo: {
        fontWeight: "800",
        fontSize: 22,
        color: "#fff",
        fontStyle: "normal",
        marginRight: 50,
    },
    AuthInput: {
        borderRadius: 31,
        backgroundColor: "#fff",
        paddingTop: 30,
        paddingBottom: 20,
        width: "100%",
    },
    searchIcon: {
        color: "#C6C9CD",
    },
    search: {
        display: "flex",
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "flex-start",
        width: "95%",
        height: 43,
        backgroundColor: "#2E2E2E",
        borderRadius: 16,
        marginLeft: "auto",
        marginRight: "auto",
        marginBottom: 15,
    },
    iconBac: {
        backgroundColor: "#7EAA00",
        width: 30,
        height: 30,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 100,
    }
})