import { Dimensions } from "react-native";

const { height, width } = Dimensions.get("screen")
import { StyleSheet } from 'react-native';
import { colors } from "../../theme/color";

export default StyleSheet.create({
    classroomHeader: {
        backgroundColor: colors.blackBackground,
        height,
        width,
    },
    downNavigationContainer: {
        position: "absolute",
        bottom: "0%",
        left: "5%",
    },
    classImage: {
        height: 235,
    },
    ImageContent: {
        paddingTop: 91,
    },
    textIM: {
        color: "#E8E5E5",
        fontSize: 32,
        fontWeight: "800",
        textAlign: "center",
    },
    textV: {
        color: "#E8E5E5",
        fontSize: 16,
        fontWeight: "700",
        textAlign: "center",
        paddingLeft: 7,
    },
    textIMC: {
        paddingHorizontal: 88,
    },
    searchBarContainer: {
        marginTop: 35,
        marginHorizontal: 65,
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        backgroundColor: colors.lightGrey,
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 16,
    },
    sectionTwo: {
        marginVertical: 24,
        width,
    },
    sectionTwoIcon: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        marginHorizontal: 79,
        gap: 20,
    },
    commonIconStyles: {
        padding: 10,
        borderRadius: 15,
    },
    sectionTwoIcon1: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        backgroundColor: "#D0212C",
        padding: 10,
        borderRadius: 15,
    },
    text: {
        color: "#E8E5E5",
        fontSize: 16,
        fontStyle: "normal",
        fontWeight: "500",
        lineHeight: 16,
    },
    sectionTwoIconDes2: {
        padding: 10,
        borderRadius: 15,
        backgroundColor: "#3200E0",
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    sectionTwoIconDes3: {
        padding: 10,
        borderRadius: 15,
        backgroundColor: "#9B51E0",
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    subject: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        width,
        marginLeft: 19,
        marginRight: 55,
        marginTop: 19,
    },
    subjectT: {
        color: "#E8E5E5",
        fontSize: 14,
        fontWeight: "500",
        padding: 15,
    },
    subjectTV1: {
        backgroundColor: "#751016",
        borderRadius: 20,
    },
    subjectTV: {
        backgroundColor: "#292929",
        borderRadius: 20,
    },
    homeSectionThree: {
        marginHorizontal: 20,
        marginBottom: 42,
        marginTop: 30,
    },
    recentBooks: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    books: {
        borderRadius: 15,
        marginBottom: 16,
        display: "flex",
        flexDirection: "row",
        alignItems: "flex-end",
        justifyContent: "space-around",
        paddingLeft: 8,
        paddingRight: 33,
        paddingVertical: 10,
    },
    bookNo: {
        borderRadius: 10,
    },
    bookNoT: {
        padding: 7,
        fontSize: 15,
        color: colors.white,
        fontWeight: "500",
    },
    bookName: {
        marginLeft: 15,
        width: 190,
    },
    bookNameT: {
        fontWeight: "500",
        fontSize: 24,
        color: "#EEF0EA",
    },
    bookNameTS: {
        fontWeight: "900",
        fontSize: 10,
        color: "#EEF0EA",
    },
    booksCon: {
        marginTop: 28,
    },
    avi: {
        color: "#fff",
        fontSize: 16,
        textAlign: "center",
        fontStyle: "normal",
        fontWeight: "500",
        lineHeight: 16,
        marginTop: 50,
    },
    sec: {
        marginTop: 30,
    },
    exo: {
        width: 350,
        height: 250,
        marginRight: "auto",
        marginLeft: "auto",
        marginTop: 20,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
    topic: {
        color: "#E8E5E5",
        fontSize: 34,
        fontWeight: "700",
        textAlign: "center",
    },
    time: {
        color: "#E8E5E5",
        fontSize: 16,
        fontWeight: "600",
        textAlign: "center",
        marginTop: 20,
    },
    timeSpan: {
        color: "#FED322",
        fontSize: 9,
        fontWeight: "600",
        textAlign: "center",
    },
    btn: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flexDirection: "row",
        gap: 20,
        marginTop: 20,
    },
    cancel: {
        width: 100,
        height: 50,
        backgroundColor: "#C94848",
        borderRadius: 15,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
    start: {
        width: 100,
        height: 50,
        backgroundColor: "#7EAA00",
        borderRadius: 15,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
    },
    cancelText: {
        color: "#fff",
        fontSize: 19,
        fontWeight: "700",
        textAlign: "center",
    },
    num: {
        backgroundColor: "#363434",
        width: 100,
        height: 30,
        marginRight: "auto",
        marginLeft: 40,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 24,
    },
    qNum: {
        color: "#fff",
        fontSize: 14,
        fontWeight: "500",
        textAlign: "center",
    },
    nP: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        flexDirection: "row",
        width: "70%",
        marginTop: 30,
    },
    normalText: {
        paddingHorizontal: 5,
        color: "#fff",
        fontSize: 14,
        fontWeight: "500",
        textAlign: "center",
    },
    selectedText: {
        paddingHorizontal: 5,
        color: "#fff",
        fontSize: 14,
        fontWeight: "700",
        textAlign: "center",
    },
    questionNumbersContainer: {
        flexDirection: "row",
        justifyContent: "center",
        marginTop: 10,
    },
    questionNumber: {
        width: 30,
        height: 30,
        backgroundColor: "#413C3C",
        borderRadius: 15,
        margin: 5,
        alignItems: "center",
        justifyContent: "center",
    },
    selectedQuestionNumber: {
        backgroundColor: "#7EAA00",
    },
    questionText: {
        color: "#fff",
    },
    optionsContainer: {
        alignItems: "center",
        display: "flex",
        flexWrap: "wrap",
        flexDirection: "row",
        justifyContent: "space-between",
        paddingHorizontal: 15,
        marginTop: 20,
    },
    option: {
        height: 44,
        borderRadius: 14,
        borderColor: "#363434",
        borderWidth: 1,
        width: "45%",
        alignItems: "center",
        display: "flex",
        flexWrap: "wrap",
        justifyContent: "center",
        padding: 10,
        marginBottom: 20,
    },
    selectedOption: {
        backgroundColor: "#363434",
    },
    selectedQuestionText: {
        color: "#fff",
    },
    timeCal: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flexDirection: "row",
        gap: 40,
        marginTop: 10,
    },
    CalTimer: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        paddingHorizontal: 25,
        paddingVertical: 10,
        borderRadius: 25,
        backgroundColor: "rgba(139, 71, 203, 0.24)",
    },
    timerVal: {
        color: "#fff",
        fontSize: 28,
        fontWeight: "500",
        textAlign: "center",
    },
});
